services:
  mongodb:
    image: mongo:8.0.15
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - bank-wise-authorization-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: bank-wise-admin
      MONGO_INITDB_ROOT_PASSWORD: bank-wise-pass
  bank-wise-authorization:
    image: alberes/bank-wise-authorization:1.0.0
    container_name: bank-wise-authorization
    ports:
      - "8080:8080"
    environment:
      USERNAME: sa
      PASSWORD:
      JPA_HIBERNATE_DDL_AUTO: update
      JPA_HIBERNATE_SHOW_SQL: true
      JPA_PROPERTIES_HIBERNATE: true
      MONGODB_URI: mongodb://bank-wise-admin:bank-wise-pass@mongodb:27017/bank-wise?authSource=admin
      MANAGEMENT_SERVER_PORT: 8081
      LOGGIN_FILE_NAME: bank-wise-authorization.log
      INTEREST_RATE: 1.02
      ACCESS_TOKEN_EXPIRATION: 300
      REFRESH_TOKEN_EXPIRATION: 600
    networks:
      - bank-wise-authorization-network
    depends_on:
      - mongodb
networks:
  bank-wise-authorization-network:
    driver: bridge