spring:
  application:
    name: bank-wise-authorization
  profiles:
    active: docker
  jackson:
    default-property-inclusion: non_null
  output:
    ansi:
      enabled: ALWAYS

  springdoc:
    override-with-generic-response: false